compute database & source for dashboard
regel/chronograf pull request #2
Opened 2018-07-16 17:27 UTC by sbettevy

find map from loudml datasources to chronograf sources and databases

2018-07-16 20:16 UTC, regel commented on ui/src/loudml/utils/query.js
>       AS ${prefix}${alias}
missing double quotes

2018-07-16 20:17 UTC, regel commented on ui/src/loudml/utils/query.js
>      const fields = features.map(f => `${f.metric}("${prefix}${f.name}")`).join(' + ')
Remplacer ${f.metric} par LAST

2018-07-16 20:18 UTC, regel commented on ui/src/loudml/utils/query.js
>       FILL(null)`
sur une seule ligne si possible?

2018-07-16 20:20 UTC, regel commented on ui/src/loudml/constants/dashboard.js
> +        // ],
Elles sont dans l'historique de git, donc elles ne sont pas perdues. Autant supprimer ces lignes?

2018-07-16 20:20 UTC, regel commented on ui/src/loudml/constants/dashboard.js
> +    // }
Elles sont dans l'historique de git, donc elles ne sont pas perdues. Autant supprimer ces lignes?

2018-07-16 20:22 UTC, regel requested changes
good job! Plusieurs propositions et fixes à confirmer, en fait les mêmes que ceux postés sur Slack.

2018-07-17 13:19 UTC, regel commented on ui/src/loudml/utils/query.js
>       FILL(null)`
GROUP BY time(bucket_interval)

2018-07-17 14:06 UTC, sbettevy commented
fixed

2018-07-17 15:32 UTC, regel approved these changes

2018-09-08 09:42 UTC, merged